- name: Install WireGuard using Docker
  hosts: my_servers
  become: yes
  tasks:
    - name: Install Docker Python module
      apt:
        name: python3-docker
        state: present
    - name: Run WireGuard Easy container
      docker_container:
        name: wg-easy
        image: weejewel/wg-easy
        state: started
        restart_policy: unless-stopped
        ports:
          - "{{ wireguard_port_udp }}:51820/udp"
          - "{{ wireguard_port_tcp }}:51821/tcp"
        volumes:
          - "/etc/wireguard/:/etc/wireguard"
        env:
          WG_HOST: "{{ wireguard_host_ip }}"
          PASSWORD: "{{ wireguard_admin_password }}"
        capabilities:
          - NET_ADMIN
          - SYS_MODULE
        sysctls:
          net.ipv4.conf.all.src_valid_mark: "1"
          net.ipv4.ip_forward: "1"

